# ref: https://github.com/docker-library/official-images
name: amd64 Docker

on: [push, pull_request, workflow_dispatch]

jobs:
  Distros:
    strategy:
      matrix:
        #platform: [amd64, arm64, riscv64]
        platform: [amd64]
        distro: [alpine, archlinux, centos, debian, fedora, opensuse, ubuntu]
      fail-fast: false
    name: ${{ matrix.platform }} • ${{ matrix.distro }} • CMake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check docker
        run: |
          docker version
          docker info
          docker buildx ls
      - name: Build env image
        run: make --directory=ci ${{ matrix.platform }}_${{ matrix.distro}}_env
      - name: Build devel image
        run: make --directory=ci ${{ matrix.platform }}_${{ matrix.distro}}_devel
      - name: Build project
        run: make --directory=ci ${{ matrix.platform }}_${{ matrix.distro}}_build
      - name: Test project
        run: make --directory=ci ${{ matrix.platform }}_${{ matrix.distro}}_test
