# ref: https://github.com/docker-library/official-images
name: amd64 Docker

on: [push, pull_request, workflow_dispatch]

jobs:
  Distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [alpine, archlinux, centos, debian, fedora, opensuse, ubuntu]
      fail-fast: false
    env:
      DISTRO: amd64_${{ matrix.distro }}
    steps:
      - uses: actions/checkout@v4
      - name: Check docker
        run: |
          docker info
          docker buildx ls
      - name: Build env image
        run: make --directory=ci ${DISTRO}_env
      - name: Build devel project
        run: make --directory=ci ${DISTRO}_devel
      - name: Build project
        run: make --directory=ci ${DISTRO}_build
      - name: Test project
        run: make --directory=ci ${DISTRO}_test
